"""add_database_indexes

Revision ID: 942766855cb0
Revises: 38515e019bc5
Create Date: 2026-02-03 18:42:04.039202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '942766855cb0'
down_revision: Union[str, Sequence[str], None] = '38515e019bc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_outgoings_deleted_at', 'outgoings', ['deleted_at'], unique=False)
    op.create_index('ix_outgoings_doc_number', 'outgoings', ['doc_number'], unique=False)
    op.create_index('ix_outgoings_status', 'outgoings', ['status'], unique=False)
    op.create_index('ix_part_movements_created_at', 'part_movements', ['created_at'], unique=False)
    op.create_index('ix_part_movements_part_id', 'part_movements', ['part_id'], unique=False)
    op.create_index('ix_part_movements_reference', 'part_movements', ['reference_type', 'reference_id'], unique=False)
    op.create_index('ix_parts_deleted_at', 'parts', ['deleted_at'], unique=False)
    op.create_index('ix_parts_is_active', 'parts', ['is_active'], unique=False)
    op.create_index('ix_parts_part_number', 'parts', ['part_number'], unique=False)
    op.create_index('ix_receivings_deleted_at', 'receivings', ['deleted_at'], unique=False)
    op.create_index('ix_receivings_doc_number', 'receivings', ['doc_number'], unique=False)
    op.create_index('ix_receivings_status', 'receivings', ['status'], unique=False)
    op.create_index('ix_requests_deleted_at', 'requests', ['deleted_at'], unique=False)
    op.create_index('ix_requests_request_number', 'requests', ['request_number'], unique=False)
    op.create_index('ix_requests_status', 'requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_requests_status', table_name='requests')
    op.drop_index('ix_requests_request_number', table_name='requests')
    op.drop_index('ix_requests_deleted_at', table_name='requests')
    op.drop_index('ix_receivings_status', table_name='receivings')
    op.drop_index('ix_receivings_doc_number', table_name='receivings')
    op.drop_index('ix_receivings_deleted_at', table_name='receivings')
    op.drop_index('ix_parts_part_number', table_name='parts')
    op.drop_index('ix_parts_is_active', table_name='parts')
    op.drop_index('ix_parts_deleted_at', table_name='parts')
    op.drop_index('ix_part_movements_reference', table_name='part_movements')
    op.drop_index('ix_part_movements_part_id', table_name='part_movements')
    op.drop_index('ix_part_movements_created_at', table_name='part_movements')
    op.drop_index('ix_outgoings_status', table_name='outgoings')
    op.drop_index('ix_outgoings_doc_number', table_name='outgoings')
    op.drop_index('ix_outgoings_deleted_at', table_name='outgoings')
    # ### end Alembic commands ###
